# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsl" do
  version "0.7.0"

  on_linux do
    on_arm do
      sha256 "e47e15ac789aa2371112776515f2b473de6539db62f9b78a1ed6b22209ebafe0"
      url "https://github.com/frostyard/nsl/releases/download/v#{version}/nsl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7e91e40cfa4f543b7aa74e600a2c76c833c335d32542c3e2820b687326715785"
      url "https://github.com/frostyard/nsl/releases/download/v#{version}/nsl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nsl"
  desc "NSpawn Subsystem for Linux — development machines on atomic hosts"
  homepage "https://github.com/frostyard/nsl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsl"

  # No zap stanza required

  caveats <<~EOS
    nsl requires an x86-64 Linux host with KVM, systemd-vmspawn, QEMU,
    UEFI firmware, virtiofsd and membership in the kvm group.
    Run nsl doctor to check host prerequisites; install them with your host's tools.
    Installation guide: https://frostyard.github.io/nsl/getting-started/install/
  EOS
end
