# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsl" do
  version "0.10.0"

  on_linux do
    on_arm do
      sha256 "6116317fb82fc08fece9b379a8b497f28f426d6c8ef3a88af54c172f98b9832e"
      url "https://github.com/frostyard/nsl/releases/download/v#{version}/nsl_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a833eec89f149b21b1ebf73944007de45fd4e9683a6b415176c9b8067eaf3887"
      url "https://github.com/frostyard/nsl/releases/download/v#{version}/nsl_linux_amd64.tar.gz"
    end
  end

  name "nsl"
  desc "NSpawn Subsystem for Linux — development machines on atomic hosts"
  homepage "https://github.com/frostyard/nsl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsl"

  # No zap stanza required

  caveats <<~EOS
    nsl requires an x86-64 Linux host with KVM, systemd-vmspawn, QEMU,
    UEFI firmware, virtiofsd and membership in the kvm group.
    Run nsl doctor to check host prerequisites; install them with your host's tools.
    Installation guide: https://frostyard.github.io/nsl/getting-started/install/
  EOS
end
