# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsl" do
  version "0.9.0"

  on_linux do
    on_arm do
      sha256 "5fd527fe354e006bc86060cbb541feb46d44da0ba1f729c8cb00769f30ba7274"
      url "https://github.com/frostyard/nsl/releases/download/v#{version}/nsl_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7cfaddcdf59c5c3e00c3dd7d53289d2d59bdaedd399538df630281d7d3ccf7a8"
      url "https://github.com/frostyard/nsl/releases/download/v#{version}/nsl_linux_amd64.tar.gz"
    end
  end

  name "nsl"
  desc "NSpawn Subsystem for Linux — development machines on atomic hosts"
  homepage "https://github.com/frostyard/nsl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsl"

  # No zap stanza required

  caveats <<~EOS
    nsl requires an x86-64 Linux host with KVM, systemd-vmspawn, QEMU,
    UEFI firmware, virtiofsd and membership in the kvm group.
    Run nsl doctor to check host prerequisites; install them with your host's tools.
    Installation guide: https://frostyard.github.io/nsl/getting-started/install/
  EOS
end
